### ISSUE TITLE
Ti filter shutter always needs a post-move wait period

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/ipython-usaxs#119]
Still getting some trouble with autoranging the amplifiers during a `tune_usaxs_optics()` scan.  Solved this in SPEC by adding some delay after the shutter move.

**Comment by prjemian** [comment]
uses `apstools.devices.EpicsOnOffShutter()` so make a subclass and force `settle_time`

**Comment by jilavsky** [comment]
logic:

* check if shutter is not in desired position
* iff: move the shutter
* iff: wait as indicated

then remove the extra sleep() instructions sprinkled throughout the USAXS configuration
