### ISSUE TITLE
tune guard slits

### ISSUE THREAD

**Issue by jilavsky** [APS-USAXS/ipython-usaxs#136]
implement tune_Gslits (from SPEC) and associated tunes

**Comment by prjemian** [comment]
Best to implement as a plan rather than making the motors tunable.  This got ugly in SPEC.  Expect here it will be *dead easy*.  Hmmm?

**Comment by prjemian** [comment]
Where's the code?

```
usaxs@usaxscontrol ~/.../profile_bluesky/startup $ grep tune_Gslits ~/spec/macros/local/*
/home/beams/USAXS/spec/macros/local/usaxs_Echange.mac:  tune_GslitsCenter  
/home/beams/USAXS/spec/macros/local/usaxs_gslit.mac:def tune_Gslits '
/home/beams/USAXS/spec/macros/local/usaxs_gslit.mac:    tune_GslitsCenter
/home/beams/USAXS/spec/macros/local/usaxs_gslit.mac:    tune_GslitsSize
/home/beams/USAXS/spec/macros/local/usaxs_gslit.mac:def tune_GslitsSize '
/home/beams/USAXS/spec/macros/local/usaxs_gslit.mac:def tune_GslitsCenter '{
```

**Comment by prjemian** [comment]
mmmm ... few hundred lines of SPEC code ... best to work it out in a new branch

**Comment by prjemian** [comment]
@jilavsky : Working on converting the guard slit tuning from SPEC now.  Here's the (draft) file to examine: https://github.com/APS-USAXS/ipython-usaxs/blob/tune-guard-slits-136/profile_bluesky/startup/51-tune_guard_slits.py

In routine `tune_GslitsCenter()` when it calls `tune_guard_slit_motor()` with guard_slit.y and then guard_slit.x,, should it find a **peak** or an **edge** of intensity vs. motor?  Which one?

You can refer to SPEC macro `_user_scan_tail_gst` which, I believe, is the same functionality.

To me, this SPEC code seems to take the derivative of intensity vs. motor:

```
    # Calculate sums of "y", "xy" and "xxy" which will be needed for x_bar and variance
    for (i=0 ; i < GSLIT_CURR_PNT ; i++) {
        if (i==0) {gslit_y[i] = 0} else {gslit_y[i]=(GSLIT_I[i-1]-GSLIT_I[i])/(GSLIT_X[i-1]-GSLIT_X[i])}
        gslit_sum_y += gslit_y[i]
        gslit_sum_xy += (GSLIT_X[i]*gslit_y[i])
        gslit_sum_xxy += (GSLIT_X[i]*GSLIT_X[i]*gslit_y[i])
    }
```

**Comment by jilavsky** [comment]
tune_guard_slit_motor()  are edge scans. This code (Jeff wrote it) should identify center of the beam (where intensity is 1/2 of maximum intensity) for . each blade and also calculates width for each blade. 

Here is my understanding of the code:
1. Tune_GslitsCenter - tunes simply x and y motors for Guard slits stage. These motors could be made normally tunable and run through standard routine - including we could add the width parameter. For now it is fixed in teh code. 

2. Tune_GslitSize - this does following
a. Open all blades of the slits by few mm (2 or more?) from their (existing) center position
b. Scan each individual blade through the beam (while others are opened) and identify for each its middle of the beam position and width. Store those values and reopen far from the beam to scan other blades. (note: Inboard/outboard are averaged and up/down are averaged, ideally each pair should be same of course.)
c. When done with all 4 blades, move all of them into the center of the beam position. This should close the beam with the slits. Then sync the Slits epics database and define the opening as 0. This basically, define center position for all blades in the Slits epics database. 
d. Calculate openings user wants from measured widths and user scaling parameters (those are typically 1.2 or so). 
e. Tell the slits epics database to open horizontal/vertical widths of the slits to user requested values.

Typical operations are:
1. run Tune_GslitsCenter. This gets run relatively routinely, may be every 2-3 days. 
2. optional run Tune_GslitSize. This seems less necessary, may be once per week or even less. 

Note: there are scaling factors which allow us to open the slits around the beam slightly more than the width to avoid edge scattering. Typical values are around 1.2. Typical beam sizes are up to 0.8mm horizontal and 0.2 mm vertical. Parameters in the code are matching these typical beam sizes. 
Typically we end up with slits opening around 0.97mm wide x 0.27 high, centered around the beam. 

Note: I did not get notification, will check my e-mail settings again.

**Comment by prjemian** [comment]
@jkirchman At this point in the SPEC macro to tune the USAXS guard slits, I have a question:

> c. When done with all 4 blades, move all of them into the center of the beam position. This should close the beam with the slits. Then sync the Slits epics database and define the opening as 0. This basically, define center position for all blades in the Slits epics database.

That is this SPEC macro code fragment (from `/home/beams/USAXS/spec/macros/local/usaxs_gslit.mac`):

```
    # redefine the motor positions so the centers are 0
    set gsltop 0   
    set gslbot 0   
    set gslout 0   
    set gslinb 0   
```

What *actually* happens here?  Does it redefine the EPICS motor record user coordinate to zero for each of the four motors?

**Comment by prjemian** [comment]
@jkirchman I'm assuming it sets the EPICS motor record's user coordinate to zero.

**Comment by jkirchman** [comment]
That's correct. In spec parlance this sets or initializes the user_angle for the motor to zero.

**Comment by prjemian** [comment]
@jkirchman Thanks
