### ISSUE TITLE
screwy PV name

### ISSUE THREAD

**Issue by jilavsky** [APS-USAXS/ipython-usaxs#137]
What is this used for?  9idcLAX:USAXS:Diode_dx (vs. 9idcLAX:USAXS_Pin:dx_in)

**Comment by prjemian** [comment]
@kmpeters : Jan has some master plans to clean up names of various PVs

We'll need a table from old to new names and need to modify various clients (caQtDM, SPEC, bluesky, HDF5).  For that reason, PV aliases might be a good idea BUT that leaves us the chance of not migrating some tools - just getting more PV names.

**Comment by prjemian** [comment]
@jilavsky Is this part of issue #145?

**Comment by jilavsky** [comment]
yes, this is mostly done or in progress. Close this one

**Comment by prjemian** [comment]
Ok
