### ISSUE TITLE
accept SPEC-style usaxs.mac file

### ISSUE THREAD

**Issue by jilavsky** [APS-USAXS/ipython-usaxs#139]
similar to #124, this file is a list of scan type, sx, sy, thickness, and sample name
ignore all the other things in it (and report as comments)

**Comment by prjemian** [comment]
A single plan would accept a file name that refers to either Excel or text content and execute accordingly.  Use a `try...except` block or develop a test for `isExcelFile()`.

**Comment by prjemian** [comment]
Use either a text file or an Excel spreadsheet (see #217).  For anything more complex, write python code and put it in a local file (see #141).
