### ISSUE TITLE
show how users can write their own local python code to use in BS session

### ISSUE THREAD

**Issue by jilavsky** [APS-USAXS/ipython-usaxs#141]

**Comment by prjemian** [comment]
Users can always write a python source code file in their present working directory and import from it.  Say they have a file `heater.py`, then `import heater` and `RE(heater.my_overnight())` might be one example.

**Comment by prjemian** [comment]
The real issue to overcome is how to *re-*import a file that has previously been imported, then edited.  Takes a little more work to do that.

**Comment by prjemian** [comment]
That **has** to be a common problem so web search turns up:

* https://stackoverflow.com/questions/1254370/reimport-a-module-in-python-while-interactive

With the example `heater.py` file, we'll need to use the `importlib` package:

```
import importlib
importlib.reload(heater)
```

or simpler:

```
from importlib import reload
reload(heater)
```
