### ISSUE TITLE
update live data software to understand BS

### ISSUE THREAD

**Issue by jilavsky** [APS-USAXS/ipython-usaxs#143]
Update live data software to manage to work with BS generated data.

**Comment by prjemian** [comment]
Also, the specplots do not update properly and this is related.  The code that recognizes "plottable" data needs to handle the way that Bluesky writes a SPEC data file *and* those files need to have sufficient information to identify the plottable data.

**Comment by prjemian** [comment]
These issues are related: #187, #193, #194, #195

**Comment by prjemian** [comment]
With `spec2nexus.__version__ 2019.0501.0'`, *specplot.py* recognizes and correctly plots the data from `tune_ar()` using today's edits for [apstools](https://github.com/BCDA-APS/apstools): #100 and #126.

**Comment by prjemian** [comment]
#198 was also related

**Comment by prjemian** [comment]
https://github.com/prjemian/spec2nexus/issues/142 is related

**Comment by prjemian** [comment]
looks finished here
