### ISSUE TITLE
Improve summarize_plan

### ISSUE THREAD

**Issue by jilavsky** [APS-USAXS/ipython-usaxs#144]
This is likely BlueSky issue. Improve summarize_plan needed:
1.  avoid crashing out from plans which need to mvoe between modes (seems to crash on hard locks)
2. avoid doing range searches in plans - no hardware should be excersized at all in summarize_plan.

**Comment by prjemian** [comment]
Both of these should be addressed by #125 and #128.  For summarize plan, might need awareness that RunEngine is idle for point 1 (above) to be successful.

**Comment by prjemian** [comment]
Both #125 and #128 fixed today.  This issue has no end since plans must be written so they don't crash out of summarize_plan().  Close for now.  Open new issues as problems happen.
