### ISSUE TITLE
Excel file sample thickness is not handled properly

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/ipython-usaxs#167]
on analysis, sample thickness is not correct when Excel batch is run

**Comment by prjemian** [comment]
We expect this value to be here: 9idcLAX:sampleThickness, while collecting SAXS data using BS this is value is 1 instead of 0.09 or whatever we set in Excel sheet.

**Comment by prjemian** [comment]
We have PV problem. We have 9idcLAX:USAXS:SampleThickness and 9idcLAX:sampleThickness, where Flyscan is using the USAXS one and SAXS/WAXS are using the one without LAX. 

This needs to be resolved.

**Comment by prjemian** [comment]
@jilavsky How will we resolve this?  One PV for sample thickness or three?

**Comment by jilavsky** [comment]
We will fix this by going to one sampleThickness, one sampleName etc. At this time we have two sampleThickness variables and three sampleNames.  On to do for May shutdown. No chance of fixing while in operations...

**Comment by prjemian** [comment]
The BS code is working fine.  Need to fix the PVs themselves.

**Comment by prjemian** [comment]
Recent work done in the IOC to change PV names (and alias back to old ones).  Perhaps that work addresses this problem as well?

**Comment by jilavsky** [comment]
This is addressed by PV changes. 
9idcLAX:sampleThickness is the one to use. All others are aliases to prevent code failure this cycle. Same for 9idcLAX:sampleName. 
Report any more PV changes needed, will sort out.
