### ISSUE TITLE
user support tools needed

### ISSUE THREAD

**Issue by jilavsky** [APS-USAXS/ipython-usaxs#193]
For user operations in BlueSky we need to have following plans / tools:
1. energy change for beamline & USAXS (spec: mv_USAXS_E)
1. a plan which will do the pre & post scan steps as spec CollectData does
1. configuration file where we can setup various values manually so they get loaded when scans are started. 
1. Linkam controls for both Linkams and example plans for data collections
1. GUI tool to write out either Excel or suitable text plan file

**Comment by prjemian** [comment]
Linkam: #208, #214, #215

**Comment by prjemian** [comment]
Item 3 needs more thought.  Let's start with users writing custom python code in experiment directory.  Users could [`reload()`](https://github.com/APS-USAXS/ipython-usaxs/issues/141#issuecomment-497500593) that file as needed.

**Comment by prjemian** [comment]
We're done with this.
