### ISSUE TITLE
Create method to run wxmtusaxs .mac files

### ISSUE THREAD

**Issue by jilavsky** [APS-USAXS/ipython-usaxs#210]
Create way to use wxmtusaxs mac files, see example for basic static sample output. 
[wxmtusaxs_macro.mac.txt](https://github.com/APS-USAXS/ipython-usaxs/files/3213555/wxmtusaxs_macro.mac.txt)

**Comment by prjemian** [comment]
The example file could be used directly with the new support from PR #217.  Handlers would need to be added for these actions in the example file:

* CURRENT_EXPERIMENT_NAME
* saxsExp  (same as SAXS?)
* USAXSscan  (same as FlyScan?)
* waxsExp  (same as WAXS?)

**Comment by prjemian** [comment]
closing this since it seems resolved, all but the handlers.
