### ISSUE TITLE
livedata not processing bluesky's FlyScan data

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/ipython-usaxs#221]
During today's testing of #217, it was noted that the [livedata WWW page](https://usaxslive.xray.aps.anl.gov/) did not show graphs of the current data.  Also, the [`actions.txt`](https://usaxslive.xray.aps.anl.gov/actions.txt) link generates a 404 error rather than expected content.

**Comment by prjemian** [comment]
Likely cause of no plottable data is that the instrument has no beam today.  (APS is operating but the other station has the beam.)  It is noted that any flyscan data collection results in such a small number of reduced data that it fails acceptance testing before plotting.

tl;dr: needs beam

**Comment by prjemian** [comment]
Checking again today.

**Comment by prjemian** [comment]
Still needs beam and new good data sets to test conclusively.

**Comment by jilavsky** [comment]
looks good now during operations
