### ISSUE TITLE
add action handlers

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/ipython-usaxs#222]
As [previously noted](https://github.com/APS-USAXS/ipython-usaxs/issues/210#issuecomment-497482238), add these handlers to support reading of text files output from the *wxmtusaxs* tool:

*    CURRENT_EXPERIMENT_NAME
*    saxsExp (same as SAXS?)
*    USAXSscan (same as FlyScan?)
*    waxsExp (same as WAXS?)

**Comment by prjemian** [comment]
What is the procedure to handle the `CURRENT_EXPERIMENT_NAME` action?  First guess:

```
        elif action == "current_experiment_name":
            nm = args[0]
            # FIXME: check this!
            yield from bps.mv(user_data.user_name, nm)
```

**Comment by jilavsky** [comment]
Yes, these are correct action handlers. 
Note, we have PV which indicates, if USAXS should run step scan or flyscan. Obviously, BS cannot do for now step scans, so USAXSscan = Flyscan, for now.

**Comment by jilavsky** [comment]
spec is simply printing in history which tab name in wxmtusaxs tool was used to generate the data. 

# /home/beams/USAXS/spec/macros/local/usaxs_commands.mac
def CURRENT_EXPERIMENT_NAME '{
	tempDummyString = "$1"
	comment "%s"  tempDummyString
}'
Therefore, this command can be ignored or printed in "spec" output file. 
NOTE: do not overwrite user name in metadata, that is obtained from scheduling system.
