### ISSUE TITLE
autoscale (amplifiers) not finding correct range

### ISSUE THREAD

**Issue by jilavsky** [APS-USAXS/ipython-usaxs#256]

**Comment by jilavsky** [comment]
Looks like the UPD amplifier is not being changed into "automatic" from "auto+background" mode.  UPD amplifier needs this for auto-ranging.  **BUT**, do **NOT** make this mode switch for the other amplifiers.

**Comment by prjemian** [comment]
commits 89d0e8b and 285047c relate to this issue

**Comment by prjemian** [comment]
Yay.  We fixed it.
