### ISSUE TITLE
preUSAXStune does not move to specific location

### ISSUE THREAD

**Issue by jilavsky** [APS-USAXS/ipython-usaxs#262]
#146 seems not to be working. preUSAXStune should move to specific location to do tunes in PV is selected. Seemed to work once manually triggered, but does not work when triggered from the code itself.

**Comment by prjemian** [comment]
related to #258, #259, #261

**Comment by prjemian** [comment]
In these plans (FlyScan, WAXS, SAXS), the number of scans (NumScansFromLastTune) must be incremented  and float time (EPOCHTimeOfLastTune) must be updated after each scan.

**Comment by prjemian** [comment]
Changeset a550508  should resolve this, by calling `preUSAXStune()` instead of `tune_usaxs_optics()` (which is a lower-level plan for staff use only).
