### ISSUE TITLE
play music at end of batch scan

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/ipython-usaxs#268]
SPEC plays some music at the end of a batch of scans.  @jilavsky insists that be added to BS

**Comment by jilavsky** [comment]
Music is triggered by watching 9idcLAX:USAXS:state. When this PV is set to "USAXS macro file done", music plays via separate Python code. SPec code sets this PV to many things, but at the end of all data collection (in spec by CollectData macro) to this specific value and that plays the music. In BS this needs to be done after run_command_file is finished.
