### ISSUE TITLE
Verify start of data collection 

### ISSUE THREAD

**Issue by jilavsky** [APS-USAXS/ipython-usaxs#287]
spec on start of data collection pushes current command file as specmacro.txt into the live data page, so it can be read remotely by staff. We should add this to run_command_file() - and include any other spec stuff done on CollectData command.

**Comment by prjemian** [comment]
This code would be added to `before_command_list()`: https://github.com/APS-USAXS/ipython-usaxs/blob/6889cc775e6eaf23480e225a2cdd301f0568f998/profile_bluesky/startup/50-plans.py#L81-L84

**Comment by prjemian** [comment]
The link from the livedata page now shows us our most recent "SPEC command file", executed by BS.
