### ISSUE TITLE
Post command file to www does not seem to work

### ISSUE THREAD

**Issue by jilavsky** [APS-USAXS/ipython-usaxs#397]
With all current changes, postCommandsListfile2WWW does not seem to work now.

**Comment by prjemian** [comment]
Confirmed this is working now:

```python
commands = get_command_list("usaxs.mac")
RE(postCommandsListfile2WWW(commands))
```

Wait 10 seconds (or so) and then confirm content: https://usaxslive.xray.aps.anl.gov/specmacro.txt

Then, modify

```python
commands = get_command_list("usaxs.mac")
RE(postCommandsListfile2WWW(commands[:4]))
```

Wait and confirm again.

Verdict: Success!
