### ISSUE TITLE
Need to check if order numbers are synced

### ISSUE THREAD

**Issue by jilavsky** [APS-USAXS/ipython-usaxs#398]
In spec we sync order numbers between USAXS, SAXS and WAXS when we start running command file
run_command_file
needs to sync when we request command file to run.

**Comment by prjemian** [comment]
This works with #396 (duplicate, sort of).

When `run_command_file()` runs:

1. order_number = max(USAXS.order_number, saxs_det.order_number, waxs_det.order_number)
1. USAXS.order_number = order_number
   - fly and step scans use the same order_number
   - this is the flyscan order_number
   - bluesky plan has to increment the order number
1. saxs_det.order_number = order_number   # saxs_det is the EPICS AD HDF1 plugin
   - EPICS AD
   - this is the image number in the HDF plugin
   - plugin auto-increments the image number
1. waxs_det.order_number = order_number   # waxs_det is the EPICS AD HDF1 plugin
   - EPICS AD
   - this is the image number in the HDF plugin
   - plugin auto-increments the image number

* later, during data collection, each technique increments its own order_number
* sample image number taken from technique-detector order_number
