### ISSUE TITLE
configure Struck SIS3820 Multi-Channel scaler in ophyd

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/ipython-usaxs#4]
Q: Is there existing ophyd device support for the SIS3820?

@tacaswell writes;

See https://github.com/NSLS-II-TES/profile_collection/blob/c0b86877d5d4fa2a626472136fb9c3d41ae853c4/startup/25-sclr.py#L37

which merges a scalerMCA and scalerCH

It is possible that you just want https://github.com/NSLS-II-TES/profile_collection/blob/master/startup/25-sclr.py#L7

**Comment by prjemian** [comment]
EPICS documentation: http://cars9.uchicago.edu/software/epics/mcaStruck.html

**Comment by prjemian** [comment]
What about [`EpicsMCA`](https://nsls-ii.github.io/ophyd/builtin-devices.html#epicsmca-and-epicsdxp)

**Comment by tacaswell** [comment]
@prjemian We should look at this while I am out in Chicago.

**Comment by prjemian** [comment]
also 575c569

**Comment by prjemian** [comment]
What else to do?

**Comment by prjemian** [comment]
test next week, changing milestone

**Comment by prjemian** [comment]
USAXS has `Struck3820` Device.  Closing for now,  Open new issue as needed.
