### ISSUE TITLE
default newUser support for data subdirectories

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/ipython-usaxs#503]
When we forget to call `newUser()` command, we don't get data folders for the area detector and fly scan HDF5 files.  Livedata stops working on files created like this.

At the end of instrument startup, call `newUser()` with a safe default.  Such as: `newUser("default_HH_MM")` (where HH and MM are the hour and minute, the month and day are set from `newUser()`).

**Comment by jilavsky** [comment]
fixed
