### ISSUE TITLE
BS defaults min step to 0.000025

### ISSUE THREAD

**Issue by jilavsky** [APS-USAXS/ipython-usaxs#513]
For step scanning we need smaller min step, for this energy 0.00001 is good value. I set this value in epics and BS overwrites it with default of 0.000025 based on energy choice. Now, this energy choice is fine when flyscanning. At this moment I have no idea how to overwrite this except to change it manually back after the command file is started. 
In spec this is solved by use of USAXS_conf.mac which allows staff overwrite specific settings by exposing those parameters. This may be needed in the future to have a parameter file which will be editable - and reloaded automatically - in current folder, like the USAXS_conf.mac.

**Comment by prjemian** [comment]
Fixed in #514
