### ISSUE TITLE
Remove limits setting from geometry changes

### ISSUE THREAD

**Issue by jilavsky** [APS-USAXS/ipython-usaxs#528]
When moving to SAXS, WAXS, and USAXS modes, we change soft limits for ax, saxs_z, and waxs_x. This is not needed anymore since these stages are protected by interlock system. This crud from times before that should be removed.

**Comment by prjemian** [comment]
Great! Constant changing of the limits has been responsible for some of the
bluesky problems you have seen.

**Comment by jilavsky** [comment]
Created branch 528-remove-limits-setting0in-geometry-changes

**Comment by jilavsky** [comment]
Did not close automatically.  (Github wants either FIX of Closes with #issue number)
